# Generated by Django 4.2.16 on 2024-12-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_studentprofile_alter_customuser_email_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
