# Generated by Django 4.2.16 on 2025-01-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ExplorePost',
        ),
    ]
