# Generated by Django 4.2.16 on 2024-12-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_post_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_file',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
