# Generated by Django 4.2.16 on 2024-12-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_studentprofile_alter_customuser_email_delete_student_and_more'),
        ('channel', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_channels', to='account.studentprofile'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
